// export const initialPerson = {
//     templateId: "1",
//     firstname: 'Obafisayo',
//     lastname: 'Abimbola',
//     name: 'Obafisayo Abimbola',
//     title: 'Software Engineer',
//     company_name: "Apex Cards",
//     company_tagline: "Future of custom cards",
//     telephone: "+1 (555) 123-4567",
//     email: "abimbolaobafisayo@gmail.com",
//     facebook_url: "https://www.facebook.com/johndoe",
//     linkedin_url: "https://www.linkedin.com/in/johndoe",
//     twitter_url: "https://twitter.com/johndoe",
//     website_url: "https://www.johndoe.com",
//     address: "123 Tech Street, San Francisco, CA 94105",
//     location: 'LG, Nigeria',
//     niche: 'Technology',
    
//     link: 'https://obafisayo-portfolio.netlify.app/',
//     cardFront: Card1Front
//     cardBack: Card1Back,
//     qrcodeClass: "absolute bottom-5 right-10",
//     logo: "https://res.cloudinary.com/dafdhu3h5/image/upload/v1727474173/clurakhvmq2gyyafnndu.png",
//     images: [
//         "idyfyg0uog5yhi8xamyr",
//         "m83bazamitfm9hvrkbem",
//         "l5mmi1atyze57eejersj",
//         "c8ssxp7ozfwgxywrka6f",
//         "oidgqkss5lwmu5psbctt",
//         "grant-whitty-vkr8QBzCIdc-unsplash_j0wlxn",
//         "Screenshot_2024-06-20_164858_jwxwdw",
//     ],
//     socials: {
//         facebook: "https://facebook.com/",
//         instagram: "https://instagram.com/",
//         linkedin: "https://linkedin.com/",
//         website: "https://website.com/",
//         twitter: "https://x.com/",
//         whatsapp: "https://web.whatsapp.com/",
//     },
// };
